### ISSUE TITLE
Where is the Bee with Cowboy Hat?

### ISSUE THREAD

**Issue by TaylorTMusic** [pensivecowboy/cowboymoji#3]
My wife needs a bee with a cowboy hat to make the joke; "bee-haw!"

Please make it happen 🐝🤠

**Comment by pensivecowboy** [comment]
Wow, that is a fantastic idea! Looks like we draw bees a bit differently 'round here with the [twemoji set](https://twemoji.twitter.com/), but it still looks mighty fine in a hat!

![bee_cowboy](https://user-images.githubusercontent.com/83992706/119246700-ac284f00-bb51-11eb-85d3-812636cc27e6.png)

bee haw!
